version: "3.1"
services:
  sme-profile:
    restart: always
    image: registry.gitlab.com/cloud-work/sme-profile:latest
    container_name: sme-profile
    logging:
      driver: "json-file"
      options:
        max-file: "3"
        max-size: "500m"
    volumes:
      - .env:/app/.env:rw
    environment: 
      NODE_ENV: 'development'
      PORT: '3000'
    expose : 
      - "3000"
    ports:
      - "3300:3000"
networks:
  default:
    external:
      name: sandbox_network

  